server:
  port: 8671

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hello-service
          uri: lb://hello-service
          predicates:
            - Path=/hello/**
        - id: testing-service
          uri: lb://testing-service
          predicates:
            - Path=/testing/**
        - id: cycle-service
          uri: lb://cycle-service
          predicates:
            - Path=/api/cycles/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"