server:
  port: 9090

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
        defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: service-register

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"