server:
    port: 8085

spring:
    application:
        name: cycle-service
    datasource:
        url: jdbc:mysql://localhost:3306/cycledb
        username: chaitanya
        password: chaitanya
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQLDialect

eureka:
    instance:
        hostname: localhost
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 20
    client:
        serviceUrl:
            defaultZone: http://localhost:9090/eureka/

management:
    endpoints:
        web:
            exposure:
                include: "*"
        jmx:
            exposure:
                include: "*"
