server:
    port: 8083

spring:
    application:
        name: cycles-service
    datasource:
        url: "jdbc:mysql://localhost:3306/cycleshop"
        username: chaitanya
        password: chaitanya
    jpa:
        properties:
            hibernate:
                naming:
                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
    private.key: classpath:app.key
    public.key: classpath:app.pub

# swagger-ui custom path
# springdoc:
#     swagger-ui:
#         path: /swagger-ui.html
    # show-actuator: true

# eureka:
#   instance:
#     hostname: localhost
#     lease-renewal-interval-in-seconds: 10
#     lease-expiration-duration-in-seconds: 20
#   client:
#     service-url:
#       defaultZone: http://localhost:9090/eureka/

management:
    endpoints:
        web:
            exposure:
                include: "*"
        jmx:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
